# run follow command to avoid error
# rustup toolchain install nightly
# rustup default nightly-x86_64-unknown-linux-gnu
#
unstable_features = false

#blank_lines_lower_bound = 1
#blank_lines_upper_bound = 2
enum_discrim_align_threshold = 60
fn_single_line = true
format_macro_matchers = true
format_strings = true
imports_indent = "Block"
match_block_trailing_comma = true
imports_granularity = "Crate"
merge_derives = true
newline_style = "Unix"
#normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 60
#wrap_comments = true
#comment_width = 100
remove_nested_parens = true
max_width = 200
ignore = [
    "patched",
]
