name: tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
        - os: macos-latest
        - os: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Run clippy
        run: cargo clippy --all-targets

      - name: Run rustfmt
        run: cargo fmt --all --check 

      - name: Build kafcat
        run: cargo build --verbose

      - name: Start plaintext kafka server
        if: matrix.os == 'ubuntu-latest'
        run: docker-compose -f tests/plaintext-server.yml up -d

      - name: Test all
        if: matrix.os == 'ubuntu-latest'
        run: cargo test --all --verbose -- --show-output
