name: tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy

      - name: Run clippy
        run: cargo clippy --all-targets

      - name: Run rustfmt
        run: cargo fmt --all --check 

      - name: Build kafcat
        run: cargo build --verbose

      - name: Start plaintext kafka server
        run: docker-compose -f tests/plaintext-server.yml up -d

      - name: Test all
        run: cargo test --all --verbose -- --show-output
