name: tests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Basic test
        run: |
          cargo build --verbose
          cargo test --all --verbose
